eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  postgres:
    datasource:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/dhl_microservice?stringtype=unspecified
      password: root
      username: postgres

  oracle:
    datasource:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@localhost:1521:XE
      password: sys123
      username: sys as sysdba

  security:
    oauth2:
      client:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/nagarro_cdcp
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

keycloak:
  admin:
    client: cdcp_admin
    client-secret: 7Z2gZms0yY50UaZr2ArxFEJPFyK0xnmw

  url: http://localhost:8080
  realm: nagarro_cdcp
  issuer-uri: http://localhost:8080/realms/nagarro_cdcp
  client: cdcp
  client-secret: 5mnYzcCVbkx2j3Qxm96TM6HZBsEIA9yP

jwt:
  auth:
    converter:
      resource-id: cdcp
      principal-attribute: preferred_username

openapi:
  info:
    server: http://localhost:8082/self-service-user-management-microservice
